import { Product, Category, Seller } from '@/types';
import { getProductPlaceholder, getSellerAvatarPlaceholder } from './imageUtils';

export const mockSellers: Seller[] = [
  {
    id: '1',
    name: 'TechStore',
    avatar: getSellerAvatarPlaceholder('TechStore'),
    rating: 4.8,
    reviewsCount: 1250,
    positiveReviewsPercent: 96,
  },
  {
    id: '2',
    name: 'FashionHub',
    avatar: getSellerAvatarPlaceholder('FashionHub'),
    rating: 4.6,
    reviewsCount: 890,
    positiveReviewsPercent: 94,
  },
  {
    id: '3',
    name: 'HomeGoods',
    avatar: getSellerAvatarPlaceholder('HomeGoods'),
    rating: 4.9,
    reviewsCount: 2100,
    positiveReviewsPercent: 98,
  },
  {
    id: '4',
    name: 'SportZone',
    avatar: getSellerAvatarPlaceholder('SportZone'),
    rating: 4.7,
    reviewsCount: 650,
    positiveReviewsPercent: 95,
  },
];

export const mockCategories: Category[] = [
  { id: 'electronics', name: 'Электроника', icon: '📱' },
  { id: 'clothing', name: 'Одежда', icon: '👕' },
  { id: 'home', name: 'Дом и сад', icon: '🏠' },
  { id: 'sports', name: 'Спорт', icon: '⚽' },
  { id: 'beauty', name: 'Красота', icon: '💄' },
  { id: 'books', name: 'Книги', icon: '📚' },
  { id: 'toys', name: 'Игрушки', icon: '🧸' },
  { id: 'food', name: 'Еда', icon: '🍔' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Смартфон Samsung Galaxy S23',
    description: 'Флагманский смартфон с отличной камерой и производительностью',
    price: 59990,
    oldPrice: 69990,
    image: getProductPlaceholder('electronics', 'Смартфон Samsung Galaxy S23'),
    category: 'electronics',
    seller: mockSellers[0],
    inStock: true,
    rating: 4.8,
    reviewsCount: 234,
  },
  {
    id: '2',
    name: 'Футболка хлопковая',
    description: 'Мягкая футболка из 100% хлопка, различные цвета',
    price: 1299,
    oldPrice: 1999,
    image: getProductPlaceholder('clothing', 'Футболка хлопковая'),
    category: 'clothing',
    seller: mockSellers[1],
    inStock: true,
    rating: 4.6,
    reviewsCount: 156,
  },
  {
    id: '3',
    name: 'Кофемашина DeLonghi',
    description: 'Автоматическая кофемашина для идеального эспрессо',
    price: 34990,
    image: getProductPlaceholder('home', 'Кофемашина DeLonghi'),
    category: 'home',
    seller: mockSellers[2],
    inStock: true,
    rating: 4.9,
    reviewsCount: 89,
  },
  {
    id: '4',
    name: 'Беговые кроссовки Nike',
    description: 'Легкие и удобные кроссовки для бега',
    price: 8990,
    oldPrice: 11990,
    image: getProductPlaceholder('sports', 'Беговые кроссовки Nike'),
    category: 'sports',
    seller: mockSellers[3],
    inStock: true,
    rating: 4.7,
    reviewsCount: 312,
  },
  {
    id: '5',
    name: 'Набор косметики L\'Oreal',
    description: 'Полный набор косметики для ежедневного ухода',
    price: 2499,
    oldPrice: 3499,
    image: getProductPlaceholder('beauty', 'Набор косметики L\'Oreal'),
    category: 'beauty',
    seller: mockSellers[1],
    inStock: true,
    rating: 4.5,
    reviewsCount: 178,
  },
  {
    id: '6',
    name: 'Книга "Война и мир"',
    description: 'Классическое произведение Льва Толстого',
    price: 599,
    image: getProductPlaceholder('books', 'Книга "Война и мир"'),
    category: 'books',
    seller: mockSellers[0],
    inStock: true,
    rating: 4.9,
    reviewsCount: 445,
  },
  {
    id: '7',
    name: 'Конструктор LEGO',
    description: 'Большой набор конструктора для детей',
    price: 3999,
    oldPrice: 4999,
    image: getProductPlaceholder('toys', 'Конструктор LEGO'),
    category: 'toys',
    seller: mockSellers[2],
    inStock: true,
    rating: 4.8,
    reviewsCount: 267,
  },
  {
    id: '8',
    name: 'Набор суши премиум',
    description: 'Свежие суши и роллы премиум качества',
    price: 1499,
    image: getProductPlaceholder('food', 'Набор суши премиум'),
    category: 'food',
    seller: mockSellers[3],
    inStock: true,
    rating: 4.6,
    reviewsCount: 123,
  },
];

